version: '3.8'

services:
  api:
    build: .
    container_name: doc_container_2
    command: npm run start
    env_file: ./.env
    depends_on:
      - mysqldb
    ports: 
      - 3001:3001
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=myoncare
      - DB_PORT=8889
    volumes:
      - .:/usr/src/app

  mysqldb:
    container_name: db-node-mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myoncare
    expose:
      - 3306
    image: mysql:8.0
    ports:
      - 8889:3306
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/

volumes: 
  db-config:
  db-data: