version: '3.8'

services:
  api:
    build:
      context: .
    container_name: doc_container_2
    depends_on:
      - mysql
    restart: always
    environment:
      - PORT=3001
      - JWT_SECRET=p4sta.w1th-b0logn3s3-s@uce
      - JWT_ALGO=HS256
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=myoncare
      - DB_PORT=3306
    networks:
      - elk
    ports: 
      - 3001:3001

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - "3306"
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0
    volumes:
      - ./mysqlDb:/var/lib/mysql
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "myoncare"
      DATABASE_HOST: mysql
      MYSQL_PASSWORD: "root"
      MYSQL_LOG_CONSOLE: "true"
    restart: always
    networks:
      - elk
    healthcheck:
      test: ["CMD", "curl", "-fk", "tcp://localhost:3306"]
      interval: 300s
      timeout: 400s
      retries: 10

networks:
  elk:
    driver: bridge

volumes: 
  db-config:
  db-data: